---

- name: Enable appindicator
  command: 'gnome-extensions enable appindicatorsupport@rgcjonas.gmail.com'
  ignore_errors: yes #This can throw an error that says the extension is already enabled
  become: yes