---

- name: Install requirements
  package:
    name: 
     - python3-psutil
     - gnome-shell-extension-dash-to-dock
    state: latest
  become: yes
  
- name: Set custom background color to true
  dconf:
     key: /org/gnome/shell/extensions/dash-to-dock/custom-background-color
     value: "false"
     state: present

- name: Set transparency mode to Fixed
  dconf:
     key: /org/gnome/shell/extensions/dash-to-dock/transparency-mode
     value: "'FIXED'"
     state: present

- name: Set opacity for dock
  dconf: 
     key: /org/gnome/shell/extensions/dash-to-dock/background-opacity
     value: '0.45'  #This value seems to work with both dark and light wallpapers
     state: present
     
- name: Display dock at the bottom
  dconf: 
     key: /org/gnome/shell/extensions/dash-to-dock/dock-position
     value: "'BOTTOM'"
     state: present

- name: Set intelligent autohide to true
  dconf:
     key: /org/gnome/shell/extensions/dash-to-dock/dock-fixed
     value: "false"
     state: present

- name: Hide mounted drives icon
  dconf:
     key: /org/gnome/shell/extensions/dash-to-dock/show-mounts
     value: "false"
     state: present
     
- name: Shrink to dash size
  dconf:
     key: /org/gnome/shell/extensions/dash-to-dock/custom-theme-shrink
     value: "true"
     state: present

- name: Hide trash icon
  dconf:
     key: /org/gnome/shell/extensions/dash-to-dock/show-trash
     value: "false"
     state: present

- name: Hide trash icon
  dconf:
     key: /org/gnome/shell/extensions/dash-to-dock/show-trash
     value: "false"
     state: present

- name: Show mounts
  dconf:
      key: /org/gnome/shell/extensions/dash-to-dock/show-mounts
      value: "true"
      state: present

- name: Pick dots as indicator
  dconf:
    key: /org/gnome/shell/extensions/dash-to-dock/running-indicator-style
    value: "'DOTS'"
    state: present

- name: Show "Show Applications"
  dconf:
     key: /org/gnome/shell/extensions/dash-to-dock/show-show-apps-button
     value: "true"
     state: present
    