---

- include_tasks: cleanup.yml

- name: Install common packages
  package: 
     name: 
       - git
       - vim
       - htop
       - powertop
       - unzip
       - flatpak
       # used as replacement for ls
       - exa 
     state: latest
  become: yes