---

- name: Add docker repository
  template: 
    src: docker_ce_repo.j2
    dest: /etc/yum.repos.d/docker-ce.repo
  become: yes

- name: Add daemon.json configuration
  template: 
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
  become: yes

- name: Install docker
  package: 
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
  become: yes

- name: Add user to docker group
  user: 
     name: "{{ansible_user}}"
     groups: docker
     append: yes
  become: yes

- name: Enable docker service at startup
  systemd:
    name: docker
    enabled: true
    state: reloaded
  become: yes

- name: Download docker-compose
  get_url: 
      url: "https://github.com/docker/compose/releases/download/{{docker_compose_version}}/docker-compose-{{ansible_system}}-{{ansible_userspace_architecture}}"
      dest: /usr/local/bin/docker-compose
      owner: "{{ansible_user}}"
      mode: 0755
      force: yes
  become: yes 