---

- name: Install jetbrains mono font family
  package:
    name: ttf-jetbrains-mono
    state: present
    become: yes

- name: Install ubuntu font family
  package:
    name: ttf-ubuntu-font-family
    state: present  
  become: yes

- name: Set default monospace font
  dconf: 
     key: /org/gnome/desktop/interface/monospace-font-name
     value: "'JetBrains Mono Bold 13'"