---

- name: Download JetBrains Mono font package
  get_url:
     url: https://download.jetbrains.com/fonts/JetBrainsMono-1.0.3.zip
     dest: /tmp/jetbrains-mono.zip

- name: Ensure folder exists
  file: 
     path: /tmp/jetbrains-mono
     state: directory

- name: Extract jebrains-mono font family
  unarchive: 
     src: /tmp/jetbrains-mono.zip
     dest: /tmp/jetbrains-mono
     owner: "{{ ansible_user }}"

- name: Ensure folder for jebrains-mono fonts exists
  file: 
     path: /usr/share/fonts/jebrains-mono
     state: directory
  become: yes

- name: Copy fonts files
  copy:
    src: "{{ item }}"
    dest: /usr/share/fonts/jebrains-mono
  with_fileglob: "/tmp/jetbrains-mono/JetBrainsMono-1.0.3/*.ttf"
  become: yes