---

- name: Download Ubuntu fonts
  get_url:
     url: https://assets.ubuntu.com/v1/0cef8205-ubuntu-font-family-0.83.zip
     dest: /tmp/ubuntu-font-family.zip

- name: Ensure folder for ubuntu fonts exists
  file: 
     path: /tmp/ubuntu-font-family
     state: directory

- name: Extract ubuntu font family
  unarchive: 
     src: /tmp/ubuntu-font-family.zip
     dest: /tmp/ubuntu-font-family
     owner: "{{ ansible_user }}"

- name: Ensure folder for ubuntu fonts exists
  file: 
     path: /usr/share/fonts/ubuntu
     state: directory
  become: yes

- name: Copy fonts files
  copy:
    src: "{{ item }}"
    dest: /usr/share/fonts/ubuntu
  with_fileglob: "/tmp/ubuntu-font-family/ubuntu-font-family-0.83/*.ttf"
  become: yes

- name: Set default monospace font
  dconf: 
     key: /org/gnome/desktop/interface/font-name
     value: "'Ubuntu 11'"

- name: Set default monospace font
  dconf: 
     key: /org/gnome/desktop/interface/document-font-name
     value: "'Ubuntu 11'"

- name: Set default monospace font
  dconf: 
     key: /org/gnome/desktop/interface/monospace-font-name
     value: "'Ubuntu Mono Bold 13'"

- name: Set default monospace font
  dconf: 
     key: /org/gnome/desktop/wm/preferences/titlebar-font
     value: "'Ubuntu 11'"