---

- include_tasks: download_ubuntu_font.yml
- include_tasks: download_jetbrains_mono.yml

- name: Set default interface font
  dconf: 
     key: /org/gnome/desktop/interface/font-name
     value: "'Ubuntu 11'"

- name: Set default document font
  dconf: 
     key: /org/gnome/desktop/interface/document-font-name
     value: "'Ubuntu 11'"

- name: Set default monospace font
  dconf: 
     key: /org/gnome/desktop/interface/monospace-font-name
     value: "'JetBrains Mono Bold 13'"

- name: Set default titlebar font
  dconf: 
     key: /org/gnome/desktop/wm/preferences/titlebar-font
     value: "'Ubuntu 11'"